# Generated by Django 3.2.8 on 2021-11-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(blank=True, max_length=100, null=True)),
                ('video_id', models.CharField(max_length=100)),
                ('video_title', models.CharField(blank=True, max_length=100, null=True)),
                ('video_thumb_url', models.CharField(blank=True, max_length=100, null=True)),
                ('video_formats', models.JSONField(blank=True, null=True)),
                ('dl_link', models.CharField(blank=True, max_length=200, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_downloaded', models.BooleanField(default=False)),
            ],
        ),
    ]
