# Generated by Django 3.2.8 on 2021-11-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_videoinfo_downloade_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoinfo',
            name='downloade_format',
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='downloaded_format',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
