# Generated by Django 3.2.8 on 2021-12-08 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_auto_20211117_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoinfo',
            old_name='dl_link',
            new_name='video_dl_link',
        ),
        migrations.RenameField(
            model_name='videoinfo',
            old_name='downloaded_format',
            new_name='video_downloaded_format',
        ),
        migrations.RenameField(
            model_name='videoinfo',
            old_name='file_name',
            new_name='video_file_name',
        ),
        migrations.RenameField(
            model_name='videoinfo',
            old_name='is_downloaded',
            new_name='video_is_downloaded',
        ),
    ]
