# Generated by Django 3.2.8 on 2021-12-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_auto_20211208_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='audio_dl_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='audio_downloaded_format',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='audio_file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='audio_is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
