# Generated by Django 3.2.8 on 2021-12-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_auto_20211208_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='video_downloaded_quality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
