# Generated by Django 3.2.8 on 2021-12-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_auto_20211211_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='audio_store_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='video_store_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
