# Generated by Django 3.2.8 on 2021-12-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_auto_20211217_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='audio_store_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='video_store_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
