# Generated by Django 3.2.8 on 2021-12-17 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0010_auto_20211217_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='video_store_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
