# Generated by Django 3.2.8 on 2021-12-17 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0011_alter_videoinfo_video_store_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='video_test_field',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
