# Generated by Django 3.2.8 on 2021-12-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0012_videoinfo_video_test_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoinfo',
            old_name='audio_store_time',
            new_name='audio_expiration_time',
        ),
        migrations.RenameField(
            model_name='videoinfo',
            old_name='video_store_time',
            new_name='video_expiration_time',
        ),
        migrations.RemoveField(
            model_name='videoinfo',
            name='video_test_field',
        ),
    ]
