# Generated by Django 3.2.8 on 2021-12-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0015_auto_20211217_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='audio_expiration_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='video_expiration_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
