# Generated by Django 3.2.8 on 2021-12-17 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0018_auto_20211217_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoinfo',
            name='audio_expiration_time',
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='video_downloaded_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 12, 43, 28, 206449)),
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='video_expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
