# Generated by Django 3.2.8 on 2021-12-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0019_auto_20211217_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='video_downloaded_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
