# Generated by Django 3.2.8 on 2021-12-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0020_alter_videoinfo_video_downloaded_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='video_expiration_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
