# Generated by Django 3.2.8 on 2021-12-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0021_alter_videoinfo_video_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='video_expiration_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
