# Generated by Django 3.2.8 on 2021-12-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0022_alter_videoinfo_video_expiration_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoinfo',
            old_name='video_downloaded_time',
            new_name='video_downloaded_time_at',
        ),
        migrations.RenameField(
            model_name='videoinfo',
            old_name='video_expiration_time',
            new_name='video_expiration_time_at',
        ),
    ]
