# Generated by Django 3.2.8 on 2021-12-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0023_auto_20211217_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='video_expiration_time_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
