# Generated by Django 3.2.8 on 2021-12-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0024_alter_videoinfo_video_expiration_time_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoinfo',
            name='video_downloaded_time_at',
        ),
    ]
