# Generated by Django 3.2.8 on 2021-12-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0025_remove_videoinfo_video_downloaded_time_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='video_remaining_time_url',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
