# Generated by Django 3.2.8 on 2021-12-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0026_videoinfo_video_remaining_time_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='video_remaining_time_url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
