# Generated by Django 3.2.8 on 2021-12-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0027_alter_videoinfo_video_remaining_time_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='audio_expiration_time_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='audio_remaining_time_url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
