# Generated by Django 3.2.8 on 2021-12-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0028_auto_20211224_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='playlist_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
