# Generated by Django 3.2.8 on 2021-12-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0029_videoinfo_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='is_playlist',
            field=models.BooleanField(default=False),
        ),
    ]
