# Generated by Django 3.2.8 on 2022-02-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0031_auto_20211229_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
